#!/bin/sh
### EXPORTS ###
export EDITOR=vi
export VISUAL=vi
### PROMPT ###
export PS1="\[\e[31m\][\[\e[m\]\[\e[33m\]\u\[\e[m\]\[\e[32m\]@\[\e[m\]\[\e[34m\]\h\[\e[m\] \[\e[35m\]\W\[\e[m\]\[\e[31m\]]\[\e[m\]\\$ "
### ALIASES ###
alias x="nvim ~/.config/Xresources"
alias conf="doas nvim /etc/nixos/configuration.nix"
alias barconf="vi ~/.config/baraction.sh"
alias sconf="vi ~/.config/spectrwm/spectrwm.conf"
alias pp="poweroff -p"
alias rp="reboot -p"
alias build="time sudo nixos-rebuild switch"
alias build-home="time home-manager switch"
alias update="sudo nix-channel --update && sudo nix-env -u && build "
alias upgrade="sudo nixos-rebuild switch --upgrade --verbose"
alias install="nix-env -f '<nixpkgs>' -iA"
alias uninstall="nix-env -e"
alias pysource="source .venv/bin/activate"
alias pyinstall="pip install"
alias pyinit="python -m venv .venv"
alias p3="python3"
alias clean="doas nix-collect-garbage && doas nix-collect-garbage -d && doas nix-store --gc && doas nix-env --delete-generations && doas nix-store --optimise"
alias q="exit"
alias c="clear"
alias search="nix search"
alias bashrc="vi ~/.bashrc"
alias mixer="alsamixer"
alias rename="mv"
alias home="home-manager edit"
alias fet.sh="~/voidrice/./fet.sh"
### VI MODE IN BASH ###
set -o vi
### AUTOCD ###
shopt -s autocd
